### ISSUE TITLE
exercise icon not rendering properly

### ISSUE THREAD

**Issue by daviddesancho** [executablebooks/sphinx-exercise#63]
### Describe the bug

When I render a jupyterbook including `exercise` directives I find that the icon used is not a pencil, but a bell.

Someone at [stackoverflow](https://stackoverflow.com/questions/77227334/exercises-not-rendering-properly-in-sphinx-with-jupyter-book) has suggested a possible culprit.

### Reproduce the bug

Information in my `requirements.txt` file:
```
sphinx
sphinx-exercise
```

Information in the `_config.yml` file:
```
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  extra_extensions:
    - sphinx_exercise
```

In the markdown notebooks:
```{exercise}
:nonumber:
:class: dropdown

Text of the exercise
```

### List your environment

```
Jupyter Book      : 0.15.1
External ToC      : 0.3.1
MyST-Parser       : 0.18.1
MyST-NB           : 0.17.1
Sphinx Book Theme : 1.0.1
Jupyter-Cache     : 0.5.0
NbClient          : 0.5.13
```
